### PR TITLE
Support Parcel 2.0.0-rc

### PR DESCRIPTION
**Pull request by akeylimepie**

### CODE REVIEW

**Comment by joshuabaker** [comment]
Works nicely in my testing. Thank you, @akeylimepie. 👍🏻 

@lukyth, please can you merge this.

**Comment by lukyth** [comment]
@joshuabaker @akeylimepie Sorry for the very late reply. Unfortunately, I don't have the access to merge PR in this repo anymore 😓 

@sotayamashita Could you help merge this PR? Or if possible, maybe I can have access to only this repo so I can maintain it.

**Comment by sotayamashita** [comment]
@lukyth OK. I am gonna merge it and let's discuss how to maintain this repo later.

**Comment by joshuabaker** [comment]
Thanks, @sotayamashita. 👍🏻 

Please can we also get an npm release out for this.

**Comment by sotayamashita** [comment]
@lukyth I give you a "maintain" role.
https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level

**Comment by lukyth** [comment]
Thanks @sotayamashita!

@joshuabaker I've published a new release to support Parcel 2. I have to make some changes to fix the test though (https://github.com/autifyhq/parcel-reporter-bundle-manifest/pull/263). Feel free to let me know if there's a problem! 😄

**Comment by joshuabaker** [comment]
Thank you very much, @lukyth 🙏🏻

**Pull request merged**
